### PR TITLE
adding ticket.id as an option when building URLs

### PR DESCRIPTION
**Pull request by luizfaias**

### CODE REVIEW

**Comment by maximeprades** [comment]
@luizfaias please fix conflicts and test latest build and give me the green light to deploy?

**Comment by luizfaias** [comment]
@maximeprades good to go now!

**Comment by maximeprades** [comment]
:+1:

**Comment by maximeprades** [comment]
@luizfaias would be awesome if you submitted this app to Labs cc @eshen

**Comment by luizfaias** [comment]
sure, I can do it but credits should go to @pi3r :smile:

**Comment by YesThatAllen** [comment]
I just want to concur.. this app has drastically changed how I use Zendesk, for the better. Nice work all!

**Comment by pi3r** [comment]
@luizfaias :bow: :pray:

**Pull request merged**
